[project]
name = "StacksPooling"
authors = []
description = ""
telemetry = true
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"
[contracts.poolTemplate1cycle1000stx]
path = "contracts/poolTemplate1cycle1000stx.clar"

[contracts.poolTemplate1cycle1000stxS]
path = "contracts/poolTemplate1cycle1000stxS.clar"

[contracts.vrf-to-uint]
path = "contracts/vrf-to-uint.clar"

[contracts.vault]
path = "contracts/vault.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
